src/Entity/Panier.php
<?php

namespace App\Entity;

use App\Repository\PanierRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PanierRepository::class)]
class Panier
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'integer', nullable: false)]
    private $quantite;

    #[ORM\OneToMany(mappedBy: 'panier', targetEntity: PanierProduit::class, orphanRemoval: true)]
    private Collection $article;

    #[ORM\OneToOne(inversedBy: 'panier', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(name: 'user_id', referencedColumnName: 'id')]
    private ?User $User = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: false)]
    private \DateTimeInterface $createdAt;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: false)]
    private \DateTimeInterface $updatedAt;

    public function __construct()
    {
        $this->article = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): self
    {
        $this->quantite = $quantite;

        return $this;
    }

    /**
     * @return Collection<int, PanierProduit>
     */
    public function getArticle(): Collection
    {
        return $this->article;
    }

    public function addArticle(PanierProduit $article): self
    {
        if (!$this->article->contains($article)) {
            $this->article->add($article);
            $article->setPanier($this);
        }

        return $this;
    }

    public function removeArticle(PanierProduit $article): self
    {
        if ($this->article->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getPanier() === $this) {
                $article->setPanier(null);
            }
        }

        return $this;
    }

    public function getCountArticle(): int

    {
        $count = 0;
        
        foreach ($this->article as $article) {
            $count += (int)$article->getQuantity();

        }

        return $count;

    }



    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
}

templates/template-parts/all-notifs.html.twig
<div class="notif">
	{% for label, messages in app.flashes %}
		{% for message in messages %}
			<div class="flash-{{ label }}">
				{{ message }}
			</div>
		{% endfor %}
	{% endfor %}
</div>

templates/template-parts/footer.html.twig
        <ul id="mentions"> 
            <li><a class="footer" href="/conditions">Conditions et cookies</a></li><br>
            <li><a class="footer" href="/nous_contacter">Nous contacter</a></li><br>
            <li><a class="footer" href="/mentions">Mentions légales</a></li><br>
            <li><a class="footer" href="/horaires">Horaires d'ouverture</a></li> 
        </ul>

        <ul id="rs"> 
            <li><a  href="https://fr-fr.facebook.com/" target="blank" rel="noreferrer noopener"><img id="fb" class="reseau-soc1"     src=" {{ asset("./assets/facebook.png") }}" alt="Facebook"></a></li><br>
            <li><a  href="https://twitter.com/?lang=fr" target="blank" rel="noreferrer noopener"><img id="twitt" class="reseau-soc3" src=" {{ asset("./assets/twitter.png") }}"  alt="Twitter"></a></li>
            <li><a  href="https://www.instagram.com/?hl=fr" target="blank" rel="noreferrer noopener"><img id="inst" class="reseau-soc2" src=" {{ asset("./assets/instagram.png") }}" alt="Instagram"></a></li><br>
        </ul>
    

templates/template-parts/general-notifs.hmtl.twig
<div class="notif">
	{% for label, messages in app.flashes(['success', 'warning', 'error']) %}
		{% for message in messages %}
			<div class="flash-{{ label }}">
				{{ message }}
			</div>
		{% endfor %}
	{% endfor %}
</div>

templates/template-parts/header.html.twig
    	
        <a href="{{path("app_home") }}"><img id="Home" class="icon" src="{{ asset("assets/logo_Sissi_Mini.png") }}" alt="Sissi logo" ></a>
		
        <h1 class="tooltipe">
		<a class="central" href="{{path("app_presentation") }}" >Biscuiterie Chocolaterie Sissi</a>
		<span class="tooltiptexte">Qui sommes nous ?</span>
		</h1>

		
     
        <a id="perso" href="{{ path('app_login') }}">
		
		{% if app.user %}
			<p><a id="logout" href="{{ path("app_logout") }}"><img id="logout" class="icon" src="{{ asset("assets/logout.png") }}" alt="Logout"></a> </p>
		{% else %}
			<img id="perso" class="icon" src="{{ asset("assets/perso.png") }}" alt="Perso" >
		{% endif %}
		</a>
        <a id="panier" href="{{ path('app_panier') }}"><img id="panier" class="icon" src="{{ asset("assets/panier2.png") }}" alt="Panier"></a>

templates/template-parts/navbar.html.twig
<nav></nav>

templates/template-parts/notifs-all.html.twig
<div class="notif">
	{% for label, messages in app.flashes %}
		{% for message in messages %}
			<div class="flash-{{ label }}">
				{{ message }}
			</div>
		{% endfor %}
	{% endfor %}
</div>

templates/template-parts/notifs-general.html.twig
<div class="notif">
	{% for label, messages in app.flashes(['success', 'warning', 'error']) %}
		{% for message in messages %}
			<div class="flash-{{ label }}">
				{{ message }}
			</div>
		{% endfor %}
	{% endfor %}
</div>

templates/template-parts/popup.html.twig
<div id="popup" data-popup="popup-1">
    <div class="verify-window">
     <h2>Cookies</h2>
      <p>Notre site utilise des cookies <b>uniquement</b> pour le bon fonctionnement.</p>
        <p align="center">Pour continuer la navigation, cliquez sur "Oui".</p>

        <div class="button-yes" data-popup-close="popup-1">
           Oui
        </div>

        <a id="non" href="https://www.google.com/" target="_parent">
            <div class="button-no">
               Non
            </div>
        </a>
    </div>
</div>